development:
  adapter: postgresql
  database: chipichipi
  pool: 5
  username: nany
  password: nany
test:
  adapter: postgresql
  database: chipichipi
  pool: 5
  username: nany
  password: nany

production:
  adapter: postgresql
  database: chipichipi
  pool: 5
  username: nany
  password: nany
